/**
 * SVG Generator Engine
 * Generates professional P&ID diagrams in SVG format
 * ISO 14617 compliant, CAD-compatible output
 */

const SVGSymbolLibrary = require('./SVGSymbolLibrary');

class SVGGenerator {
    constructor(options = {}) {
        this.width = options.width || 1200;
        this.height = options.height || 800;
        this.padding = options.padding || 50;
        this.symbolLibrary = new SVGSymbolLibrary();

        // Color scheme for different pipe services
        this.pipeColors = {
            suction: '#0066CC',      // Blue - low pressure
            discharge: '#CC0000',    // Red - high pressure  
            liquid: '#00CC66',       // Green - liquid line
            hot_gas: '#FF6600',      // Orange - hot gas
            refrigerant: '#9900CC',  // Purple - general refrigerant
            default: '#000000'       // Black - default
        };

        // Pipe widths by size
        this.pipeWidths = {
            small: 2,
            medium: 3,
            large: 4
        };
    }

    /**
     * Generate complete SVG diagram from P&ID data
     */
    generate(pidData) {
        console.log('[SVGGenerator] Generating SVG diagram...');
        console.log(`[SVGGenerator]   Components: ${pidData.components?.compressors?.length || 0} compressors, ${pidData.components?.evaporators?.length || 0} evaporators`);

        // Build SVG structure
        const svg = {
            tag: 'svg',
            attrs: {
                xmlns: 'http://www.w3.org/2000/svg',
                'xmlns:xlink': 'http://www.w3.org/1999/xlink',
                width: this.width,
                height: this.height,
                viewBox: `0 0 ${this.width} ${this.height}`,
                version: '1.1'
            },
            children: []
        };

        // Add title and description
        svg.children.push({
            tag: 'title',
            content: pidData.metadata?.title || 'P&ID Diagram'
        });

        svg.children.push({
            tag: 'desc',
            content: `Generated by GFDDE - Capacity: ${pidData.requirements?.cooling_capacity || 'N/A'} kW`
        });

        // Add definitions (symbol library)
        svg.children.push(this.createDefinitions());

        // Add background
        svg.children.push(this.createBackground());

        // Add layers
        svg.children.push(this.createEquipmentLayer(pidData));
        svg.children.push(this.createPipingLayer(pidData));
        svg.children.push(this.createValvesLayer(pidData));
        svg.children.push(this.createInstrumentsLayer(pidData));
        svg.children.push(this.createAnnotationsLayer(pidData));

        // Add border and title block
        svg.children.push(this.createBorder());
        svg.children.push(this.createTitleBlock(pidData));

        console.log('[SVGGenerator] ✅ SVG generated successfully');

        return this.renderToString(svg);
    }

    /**
     * Create definitions section with all symbols
     */
    createDefinitions() {
        const defs = {
            tag: 'defs',
            children: []
        };

        // Add all symbols from library
        const symbols = this.symbolLibrary.getAllSymbolIds();
        symbols.forEach(symbolId => {
            const symbol = this.symbolLibrary.getSymbol(symbolId);
            defs.children.push(this.parseSVGString(symbol.svg));
        });

        // Add arrow marker for flow direction
        defs.children.push({
            tag: 'marker',
            attrs: {
                id: 'arrowhead',
                markerWidth: '10',
                markerHeight: '10',
                refX: '5',
                refY: '3',
                orient: 'auto',
                markerUnits: 'strokeWidth'
            },
            children: [{
                tag: 'path',
                attrs: {
                    d: 'M0,0 L0,6 L9,3 z',
                    fill: 'currentColor'
                }
            }]
        });

        return defs;
    }

    /**
     * Create background layer
     */
    createBackground() {
        return {
            tag: 'rect',
            attrs: {
                x: 0,
                y: 0,
                width: this.width,
                height: this.height,
                fill: '#FFFFFF'
            }
        };
    }

    /**
     * Create equipment layer
     */
    createEquipmentLayer(pidData) {
        const layer = {
            tag: 'g',
            attrs: {
                id: 'layer-equipment',
                'data-layer': 'equipment'
            },
            children: []
        };

        // Add compressors
        if (pidData.components?.compressors) {
            pidData.components.compressors.forEach((comp, index) => {
                const position = comp.position || this.calculatePosition('compressor', index, pidData);
                const symbolType = comp.type === 'screw' ? 'compressor_screw' : 'compressor_reciprocating';

                layer.children.push(this.createEquipmentInstance(
                    symbolType,
                    position,
                    comp.tag || `CMP-${index + 1}`,
                    comp
                ));
            });
        }

        // Add evaporators
        if (pidData.components?.evaporators) {
            pidData.components.evaporators.forEach((evap, index) => {
                const position = evap.position || this.calculatePosition('evaporator', index, pidData);

                layer.children.push(this.createEquipmentInstance(
                    'evaporator',
                    position,
                    evap.tag || `EVP-${index + 1}`,
                    evap
                ));
            });
        }

        // Add condensers
        if (pidData.components?.condensers) {
            pidData.components.condensers.forEach((cond, index) => {
                const position = cond.position || this.calculatePosition('condenser', index, pidData);

                layer.children.push(this.createEquipmentInstance(
                    'condenser',
                    position,
                    cond.tag || `COND-${index + 1}`,
                    cond
                ));
            });
        }

        // Add vessels/receivers
        if (pidData.components?.vessels) {
            pidData.components.vessels.forEach((vessel, index) => {
                const position = vessel.position || this.calculatePosition('vessel', index, pidData);

                layer.children.push(this.createEquipmentInstance(
                    'vessel_horizontal',
                    position,
                    vessel.tag || `V-${index + 1}`,
                    vessel
                ));
            });
        }

        return layer;
    }

    /**
     * Create equipment instance with label
     */
    createEquipmentInstance(symbolId, position, tag, data) {
        const symbol = this.symbolLibrary.getSymbol(symbolId);

        const group = {
            tag: 'g',
            attrs: {
                'data-component-type': symbolId,
                'data-tag': tag,
                transform: `translate(${position.x}, ${position.y})`
            },
            children: []
        };

        // Symbol
        group.children.push({
            tag: 'use',
            attrs: {
                'xlink:href': `#${symbolId}`,
                x: 0,
                y: 0
            }
        });

        // Tag label
        group.children.push({
            tag: 'text',
            attrs: {
                x: symbol.width / 2,
                y: symbol.height + 15,
                'text-anchor': 'middle',
                'font-family': 'Arial, sans-serif',
                'font-size': '12',
                'font-weight': 'bold',
                fill: '#000000'
            },
            content: tag
        });

        // Capacity label (if available)
        if (data.capacity) {
            group.children.push({
                tag: 'text',
                attrs: {
                    x: symbol.width / 2,
                    y: symbol.height + 28,
                    'text-anchor': 'middle',
                    'font-family': 'Arial, sans-serif',
                    'font-size': '10',
                    fill: '#666666'
                },
                content: `${data.capacity} kW`
            });
        }

        return group;
    }

    /**
     * Calculate default position for equipment
     */
    calculatePosition(type, index, pidData) {
        const baseY = this.height / 2;
        const spacing = 250;

        const positions = {
            compressor: { x: 150, y: baseY },
            condenser: { x: 450, y: baseY - 150 },
            vessel: { x: 650, y: baseY },
            evaporator: { x: 850 + (index * spacing), y: baseY + 150 }
        };

        return positions[type] || { x: 100 + (index * spacing), y: baseY };
    }

    /**
     * Create piping layer
     */
    createPipingLayer(pidData) {
        const layer = {
            tag: 'g',
            attrs: {
                id: 'layer-piping',
                'data-layer': 'piping'
            },
            children: []
        };

        // Generate piping connections
        if (pidData.piping) {
            pidData.piping.forEach((pipe, index) => {
                const path = this.routePipe(pipe.from, pipe.to, pipe.waypoints);

                layer.children.push({
                    tag: 'path',
                    attrs: {
                        d: path,
                        stroke: this.pipeColors[pipe.service] || this.pipeColors.default,
                        'stroke-width': this.pipeWidths[pipe.size] || this.pipeWidths.medium,
                        fill: 'none',
                        'data-pipe-id': pipe.id || `pipe-${index}`,
                        'data-service': pipe.service,
                        'marker-end': pipe.showArrow ? 'url(#arrowhead)' : ''
                    }
                });

                // Add pipe label
                if (pipe.label) {
                    const midpoint = this.calculateMidpoint(pipe.from, pipe.to);
                    layer.children.push({
                        tag: 'text',
                        attrs: {
                            x: midpoint.x,
                            y: midpoint.y - 5,
                            'text-anchor': 'middle',
                            'font-family': 'Arial, sans-serif',
                            'font-size': '9',
                            fill: '#333333'
                        },
                        content: pipe.label
                    });
                }
            });
        }

        return layer;
    }

    /**
     * Route pipe with orthogonal (manhattan) routing
     */
    routePipe(from, to, waypoints = []) {
        if (waypoints && waypoints.length > 0) {
            // Custom waypoints provided
            let path = `M ${from.x},${from.y}`;
            waypoints.forEach(wp => {
                path += ` L ${wp.x},${wp.y}`;
            });
            path += ` L ${to.x},${to.y}`;
            return path;
        }

        // Auto orthogonal routing
        const dx = to.x - from.x;
        const dy = to.y - from.y;

        if (Math.abs(dx) > Math.abs(dy)) {
            // Horizontal first
            const midX = from.x + dx / 2;
            return `M ${from.x},${from.y} L ${midX},${from.y} L ${midX},${to.y} L ${to.x},${to.y}`;
        } else {
            // Vertical first
            const midY = from.y + dy / 2;
            return `M ${from.x},${from.y} L ${from.x},${midY} L ${to.x},${midY} L ${to.x},${to.y}`;
        }
    }

    /**
     * Calculate midpoint of pipe
     */
    calculateMidpoint(from, to) {
        return {
            x: (from.x + to.x) / 2,
            y: (from.y + to.y) / 2
        };
    }

    /**
     * Create valves layer
     */
    createValvesLayer(pidData) {
        const layer = {
            tag: 'g',
            attrs: {
                id: 'layer-valves',
                'data-layer': 'valves'
            },
            children: []
        };

        if (pidData.valves) {
            pidData.valves.forEach((valve, index) => {
                const symbolType = this.getValveSymbol(valve.type);
                const symbol = this.symbolLibrary.getSymbol(symbolType);

                layer.children.push({
                    tag: 'use',
                    attrs: {
                        'xlink:href': `#${symbolType}`,
                        x: valve.position.x,
                        y: valve.position.y,
                        'data-valve-type': valve.type,
                        'data-tag': valve.tag || `V-${index + 1}`
                    }
                });
            });
        }

        return layer;
    }

    /**
     * Get valve symbol ID from valve type
     */
    getValveSymbol(type) {
        const mapping = {
            'manual': 'valve_manual',
            'check': 'valve_check',
            'relief': 'valve_relief',
            'solenoid': 'valve_solenoid',
            'expansion': 'valve_expansion'
        };
        return mapping[type] || 'valve_manual';
    }

    /**
     * Create instruments layer
     */
    createInstrumentsLayer(pidData) {
        return {
            tag: 'g',
            attrs: {
                id: 'layer-instruments',
                'data-layer': 'instruments'
            },
            children: []
        };
    }

    /**
     * Create annotations layer
     */
    createAnnotationsLayer(pidData) {
        return {
            tag: 'g',
            attrs: {
                id: 'layer-annotations',
                'data-layer': 'annotations'
            },
            children: []
        };
    }

    /**
     * Create border
     */
    createBorder() {
        return {
            tag: 'rect',
            attrs: {
                x: this.padding / 2,
                y: this.padding / 2,
                width: this.width - this.padding,
                height: this.height - this.padding,
                stroke: '#000000',
                'stroke-width': 2,
                fill: 'none'
            }
        };
    }

    /**
     * Create title block
     */
    createTitleBlock(pidData) {
        const tbWidth = 300;
        const tbHeight = 80;
        const x = this.width - tbWidth - this.padding;
        const y = this.height - tbHeight - this.padding;

        const group = {
            tag: 'g',
            attrs: { id: 'title-block' },
            children: []
        };

        // Border
        group.children.push({
            tag: 'rect',
            attrs: {
                x, y,
                width: tbWidth,
                height: tbHeight,
                stroke: '#000000',
                'stroke-width': 1,
                fill: '#F8F8F8'
            }
        });

        // Title
        group.children.push({
            tag: 'text',
            attrs: {
                x: x + 10,
                y: y + 20,
                'font-family': 'Arial, sans-serif',
                'font-size': '14',
                'font-weight': 'bold'
            },
            content: pidData.metadata?.title || 'Ammonia Refrigeration System'
        });

        // Project info
        const info = [
            `Capacity: ${pidData.requirements?.cooling_capacity || 'N/A'} kW`,
            `Refrigerant: ${pidData.requirements?.refrigerant || 'R717'}`,
            `Date: ${new Date().toLocaleDateString()}`
        ];

        info.forEach((text, i) => {
            group.children.push({
                tag: 'text',
                attrs: {
                    x: x + 10,
                    y: y + 40 + (i * 12),
                    'font-family': 'Arial, sans-serif',
                    'font-size': '10'
                },
                content: text
            });
        });

        return group;
    }

    /**
     * Parse SVG string to object
     */
    parseSVGString(svgString) {
        // For embedded SVG strings, return as raw SVG
        if (typeof svgString === 'string' && svgString.trim().startsWith('<')) {
            return {
                rawSVG: svgString.trim()
            };
        }

        return null;
    }

    /**
     * Parse attributes string
     */
    parseAttributes(attrString) {
        const attrs = {};
        const regex = /([a-z-]+)="([^"]*)"/gi;
        let match;
        while ((match = regex.exec(attrString)) !== null) {
            attrs[match[1]] = match[2];
        }
        return attrs;
    }

    /**
     * Render SVG object to string
     */
    renderToString(svgObject) {
        if (svgObject.rawSVG) {
            return svgObject.rawSVG;
        }

        let svg = `<${svgObject.tag}`;

        // Add attributes
        if (svgObject.attrs) {
            Object.entries(svgObject.attrs).forEach(([key, value]) => {
                svg += ` ${key}="${value}"`;
            });
        }

        svg += '>';

        // Add content
        if (svgObject.content) {
            svg += svgObject.content;
        }

        // Add children
        if (svgObject.children) {
            svgObject.children.forEach(child => {
                svg += this.renderToString(child);
            });
        }

        svg += `</${svgObject.tag}>`;

        return svg;
    }
}

module.exports = SVGGenerator;
